### ISSUE TITLE
Bowtie reports "Reads file contained a pattern with more than 1024 quality values."

### ISSUE THREAD

**Issue by dz-enigmatologist** [rnnh/bioinfo-notebook#1]
When the following command is run for human genome, I get the following error. 
I tried writing a script to check if the fastq files had more 1024 chars but it did not. Can you please direct me to what i may be doing wrong. 
thank you,
Deepta.

/Users/SBRGMBA/Downloads/MACE-1.2/bowtie-1.3.1-macos-x86_64/bowtie-align-s --wrapper basic-0 -S -q -m 1 -x /Users/SBRGMBA/Downloads/hg19_c.ebwt/hg19_c /Users/SBRGMBA/Downloads/MACE-1.2/rawSeqMACEexample/SRR346401.fastq CTCF_replicate1.sam
Reads file contained a pattern with more than 1024 quality values.
Please truncate reads and quality values and and re-run Bowtie

I followed the instructions from here
https://sourceforge.net/projects/chipexo/files/
https://github.com/rnnh/bioinfo-notebook
https://rnnh.github.io/bioinfo-notebook/docs/bowtie.html

**Comment by rnnh** [comment]
Hey Deepta,

I'd suggest trying [bowtie2 instead of bowtie](https://rnnh.github.io/bioinfo-notebook/docs/bowtie2.html), and using [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) to investigate the quality of sequencing reads. I hope that helps.

Kind regards,
Ronan
